### ISSUE TITLE
RGB lines to cut for SHVC-CPU-01 may be incorrect

### ISSUE THREAD

**Issue by Firebrandx** [borti4938/SNES_RGB_Bypass#3]
Someone posted a photo of this area on the board asking for clarification on the cut points. In the guide lists the following information:

"cut traces for R', G' and B' right before the MultiAV (but behind C44, C46 and C47)"

However, C46 goes into pin 3, not pin 4, and the ceramic cap for it is a different color. Just visually inspecting the photo, I suspect C44, C45, and C47 are the RGB ceramic caps. Might want to double-check this to make sure.

![Possible bad cuts for SVHC-CPU-01](https://user-images.githubusercontent.com/27827688/169537553-6802c2a8-4e56-4c88-b30c-b59e4c501516.jpg)

**Comment by mzryz** [comment]
Thanks @Firebrandx (I'm the same guy from FB you were helping) I succesfully installed the board and took photos. Another thing I would change on the instructions is: When it says to install the SMD resistors on the board, it just says install, nothing mentioned about removing the original components. So It should say remove & then install the parts, otherwise people might think they need to stack them or something.

Board before removing SMD resistors:

![1  before smd remove copy](https://user-images.githubusercontent.com/23113373/169647009-63076c11-489b-4a2f-888e-4be27edc1508.jpg)
Board after removing SMD resistors:
![2  after smd remove copy](https://user-images.githubusercontent.com/23113373/169646828-e6fa3dfc-6bb7-47de-ada8-5bc1086abade.jpg)
New SMD resistors are installed:
![3  new smd installed](https://user-images.githubusercontent.com/23113373/169646406-ca67b854-f7bf-4e6b-bdec-5c17054d2fa7.jpg)
Isolate the rear of the bypass board with kapton tape:
![4  isolate back](https://user-images.githubusercontent.com/23113373/169646409-0cdfb8e7-d508-4848-a416-c40bb4142fe4.jpg)
Install the bypass board:
![5  install rgb bypass](https://user-images.githubusercontent.com/23113373/169646411-725c1a7d-8687-4201-a2a1-40824461d928.jpg)
Install the R, G & B wires:
![6  install rgb wires](https://user-images.githubusercontent.com/23113373/169646412-81eeb70c-ea20-44e4-ba79-3607832bb191.jpg)

**Comment by borti4938** [comment]
Sorry, "C44, C46 and C47" was incorrect, "C44, C45 and C47" should it be. See also here: https://shmups.system11.org/viewtopic.php?p=1492311#p1492311
